apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-web-app
  labels:
    app: jupyter-web-app
spec:
  selector:
    matchLabels:
      app: jupyter-web-app
  template:
    metadata:
      annotations:
        data.statcan.gc.ca/inject-blob-volumes: "true"
      labels:
        app: jupyter-web-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: jupyter-web-app
          imagePullPolicy: IfNotPresent
          image: nginx-test-dev:latest
          env:
            - name: UI
              value: default
            - name: USERID_HEADER
              value: null
              valueFrom:
                configMapKeyRef:
                  name: kubeflow-config
                  key: userid-header
            - name: USERID_PREFIX
              value: null
              valueFrom:
                configMapKeyRef:
                  name: kubeflow-config
                  key: userid-prefix
            - name: KUBECOST_URL
              value: http://kubecost-cost-analyzer.kubecost-system.svc.cluster.local:9090
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            # - name:logos-volume
            #   mountPath: /static/assets/logos/group-one-icon.svg
            #   subPath: group-one-icon.svg
            # - name: logos-volume
            #   mountPath: /static/assets/logos/group-one-logo.svg
            #   subPath: group-one-logo.svg
            # - name: logos-volume
            #   mountPath: /static/assets/logos/group-two-icon.svg
            #   subPath: group-two-icon.svg
            # - name: logos-volume
            #   mountPath: /static/assets/logos/group-two-logo.svg
            #   subPath: group-two-logo.svg
            # - name: logos-volume
            #   mountPath: /static/assets/logos/jupyter-icon.svg
            #   subPath: jupyter-icon.svg
            # - name: logos-volume
            #   mountPath: /static/assets/logos/jupyterlab-logo.svg
            #   subPath: jupyterlab-logo.svg
            # - name: logos-volume
            #   mountPath: /src/apps/default/static/assets/logos
        - name: nginx
          image: docker.io/nginxinc/nginx-unprivileged:1.21-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.25"
              memory: "250Mi"
            requests:
              cpu: "0.25"
              memory: "250Mi"
          volumeMounts:
            - name: jwa-nginx-configuration
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: static-files
              mountPath: /etc/nginx/html/
          ports:
            - name: http
              containerPort: 8080
      initContainers:
        - name: copy-jwa-static-files
          # Change for the image I just built
          image: nginx-test-dev:latest
          # image: k3d-s3proxy-registry:5050/s3proxy-dev:latest
          command: [sh, -c]
          args: ["cp -r /static/* /etc/nginx/html/"]
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/nginx/html/
              name: static-files
      volumes:
        - name: jwa-nginx-configuration
          configMap:
            name: jwa-nginx-configuration
        - name: static-files
          emptyDir: {}
        - configMap:
            name: jupyter-web-app-config
          name: config-volume
        # - configMap:
        #     name: jupyter-web-app-logos
        #   name: logos-volume
