apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - configs/spawner_ui_config.yaml
  # behavior: replace
  name: jupyter-web-app-config
  # TODO: Will need to put the namespace: kubeflow back when ready for dev
  namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - deployment.yaml
  - nginx-config.yaml
  - configs/kubeflow-config.yaml