name: Build

on:
  pull_request:
    branches:
      - jupyter-apis-aaw2.0

env:
  K3D_VERSION: 4.4.7
  KUBECTL_VERSION: 1.21.2
  KUSTOMIZE_VERSION: 4.1.3
  REGISTRY_NAME: k8scc01covidacr

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.20.5'

    - name: Gather dependencies
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/bin/

        # install kubectl
        curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o ${GITHUB_WORKSPACE}/bin/kubectl && chmod +x ${GITHUB_WORKSPACE}/bin/kubectl

        # install kustomize
        curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz -o kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz && tar -zxvf kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz && chmod +x kustomize && mv kustomize ${GITHUB_WORKSPACE}/bin/kustomize

        # install k3d
        curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v${K3D_VERSION} bash

        # install taskfile
        curl -sL https://taskfile.dev/install.sh | sh

        # install yq
        sudo snap install yq

    - name: GitHub Path
      run: |
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Build Binary
      run: |
        task go:build

    - name: Linting
      run: |
        task go:vet