name: JWA Frontend Tests
on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'

jobs:
  run-ui-tests:
    name: UI tests with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node version to 12
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install Kubeflow common library dependecies
        run: |
          cd frontend/common/kubeflow-common-lib
          npm i
          npm run build
          npm link ./dist/kubeflow
      - name: Install JWA dependencies
        run: |
          cd frontend/jupyter
          npm i
          npm link kubeflow
      - name: Serve UI & run Cypress tests in Chrome and Firefox
        run: |
          cd frontend/jupyter
          npm start & npx wait-on http://localhost:4200
          npm run ui-test-ci-all