name: publish
on:
  push:
    branches:
      - main
      - jupyter-apis-aaw2.0
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
  schedule: 
    - cron: '0 23 * * *'

env:
  REGISTRY_NAME: k8scc01covidacr
  DEV_REGISTRY_NAME: k8scc01covidacrdev
  TRIVY_VERSION: "v0.43.1"
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    # Determine if pushing to ACR or DEV ACR
    - name: Set ENV variables for a PR
      if: github.event_name == 'pull_request'
      run: echo "REGISTRY=${{env.DEV_REGISTRY_NAME}}.azurecr.io" >> "$GITHUB_ENV"
   
    - name: Set ENV variable for pushes to master
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: echo "REGISTRY=${{env.REGISTRY_NAME}}.azurecr.io" >> "$GITHUB_ENV"

    # Push image to ACR
    # Pushes if this is a push to master or an update to a PR that has auto-deploy label
    - name: Test if we should push to ACR
      id: should-i-push
      if: |
        github.event_name == 'push' ||
        (
          github.event_name == 'pull_request' &&
          contains( github.event.pull_request.labels.*.name, 'auto-deploy')
        )
      run: echo "::set-output name=boolean::true"

    - uses: actions/checkout@master

    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Connect to Azure DEV Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.DEV_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.DEV_REGISTRY_USERNAME }}
        password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

    
    - name: Build image locally
      run: |
        docker build -f Dockerfile -t localhost:5000/jupyter-apis-aaw2:${{ github.sha }} .
        docker push localhost:5000/jupyter-apis-aaw2:${{ github.sha }}
        docker image prune
    
    - name: Aqua Security Trivy image scan
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
        trivy image localhost:5000/jupyter-apis-aaw2:${{ github.sha }} --exit-code 1 --timeout=20m --security-checks vuln --severity CRITICAL
  
    # Run Dockle
    - name: Run dockle
      uses: goodwithtech/dockle-action@main
      with:
        image: localhost:5000/jupyter-apis-aaw2:${{ github.sha }}
        format: 'list'
        exit-code: '0'
        exit-level: 'fatal'
        ignore: 'DKL-DI-0006'

    # Container build and push to a Azure Container registry (ACR)
    - name: Push to ACR if necessary
      if: steps.should-i-push.outputs.boolean == 'true'
      run: |
        docker pull localhost:5000/jupyter-apis-aaw2:${{ github.sha }}
        docker tag localhost:5000/jupyter-apis-aaw2:${{ github.sha }} ${{ env.REGISTRY }}/jupyter-apis-aaw2:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/jupyter-apis-aaw2:${{ github.sha }}

    - name: Slack Notification
      if: failure() && github.event_name=='schedule'
      uses: act10ns/slack@v1
      with:
        status: failure
        message: jupyter-apis build failed. https://github.com/StatCan/jupyter-apis/actions/runs/${{github.run_id}}
